language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install numpy utm future lxml pymavlink
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below